### ISSUE TITLE
cannot download images

### ISSUE THREAD

**Issue by fatshotty** [ruuk/plugin.image.google#1]
Hi,
I experiencing this issue:
- I search images, for example "horses"
- I got result list
- Context Menu on an item
- Click on "download image"
- Error: set 'save path' first

I've already configured the 'saved path' pointing to my local folder: `/media/images` but problem is still there. Yes, my folder is correctly set for read/write permissions
Is it only my case?

Thanks in advance

**Comment by ruuk** [comment]
This plugin is deprecated.
